serverlessworkflow/sdk-go

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/question.md
.github/OWNERS
.github/PULL_REQUEST_TEMPLATE.md

Simple addition of CODEOWNERS and OWNERS files.

Adding owners, codeowners and templates

---

MAINTAINERS.md
maintainer_guidelines.md

Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>
Adds the maintainers info to this repo and maintainers guidelines. All SDK repos should have these.

Adding maintainers and maintainers guidelines docs

---

hack/generate-spec-types.sh

Closes #3, #4 - Update specification schema path, regenerate types

---

.github/workflows/Go-SDK-PR-Check.yaml

Fixing CI bugs and typos

---

model/zz_generated.types_workflow.go
parser/parser_test.go
parser/testdata/provisionorders.sw.json

This PR aligns the SDK with the changes introduced by https://github.com/serverlessworkflow/specification/pull/175

[1.0.x] Incorporating Errors Schema

---

model/zz_generated.types_workflow.go
parser/parser_test.go
parser/testdata/provisionorders.sw.json

[master] Incorporating Errors Schema

---

.github/workflows/Go-SDK-PR-Check.yaml
README.md
maintainer_guidelines.md
parser/testdata/applicationrequest.url.json

Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

fix main branch name

---

README.md

Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

Adding status to readme

---

model/unmarshal_json.go
parser/parser.go

Signed-off-by: someshkoli <kolisomesh27@gmail.com>
Fixes  fix G107 G304 gosec warnings
Done as part of bugbash <3 

(bugbash) fix G107 G304 gosec warnings

---

model/unmarshal_json.go

Signed-off-by: arcolife <archit.py@gmail.com>
Nested if can be replaced with else-if. 
_why we need it?_: 🤷🏼‍♂️ 
not a bug? 🤷🏼‍♂️ 

Nested if can be replaced with else-if

---

code-of-conduct.md

Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>

Bugsmash erros

---

README.md
go.mod
go.sum
model/event.go
parser/parser.go
parser/parser_test.go

Fixes (#34) the v2 tag release
After merging this PR, I'll release 2.1.0 with the latest changes so people will be able to download the correct latest module.

Fix #34 - Add v2 module to go.mod

---

README.md
model/retry.go

In this PR we wrap up the main branch for the 2.0.1 release to stabilize the v0.6 support.

Patch for release 2.0.1

---

parser/testdata/workflows/applicationrequest-issue16.sw.yaml
parser/testdata/workflows/applicationrequest-issue69.json
parser/testdata/workflows/applicationrequest.json
parser/testdata/workflows/applicationrequest.multiauth.json
parser/testdata/workflows/applicationrequest.rp.json
parser/testdata/workflows/applicationrequest.url.json
parser/testdata/workflows/checkinbox.cron-test.sw.yaml
parser/testdata/workflows/checkinbox.sw.yaml
parser/testdata/workflows/eventbaseddataandswitch.sw.json
parser/testdata/workflows/eventbasedgreeting.sw.json
parser/testdata/workflows/eventbasedgreeting.sw.p.json
parser/testdata/workflows/eventbasedgreetingexclusive.sw.json
parser/testdata/workflows/eventbasedgreetingnonexclusive.sw.json
parser/testdata/workflows/greetings-constants-file.sw.yaml
parser/testdata/workflows/greetings-secret-file.sw.yaml
parser/testdata/workflows/greetings-secret.sw.yaml
parser/testdata/workflows/greetings.sw.json
parser/testdata/workflows/greetings.sw.yaml
parser/testdata/workflows/witherrors/applicationrequest-issue44.json
parser/testdata/workflows/witherrors/applicationrequest.auth.invalid.format.json
parser/testdata/workflows/witherrors/applicationrequest.authdupl.json

- origin test examples use jsonpath（and without expressionLang configured）, change it to jq

feat(*): change test resources expression to jq

---

parser/parser_test.go

allows maintainer to run test on a case level instead of the whole test suite

Refactor table test

---

model/event_state.go

refactor(*): cleanup unused commented code

---

model/callback_state.go
model/states.go

Fixed https://github.com/serverlessworkflow/sdk-go/issues/117

fix(117): split callback state to separate file

---

.github/labeler.yml
.github/labels.yml
.github/workflows/prow_commands.yml
.github/workflows/prow_cron_pull_request_merge.yml
.github/workflows/prow_remove_lgtm.yml
.github/workflows/pull_request_labeler.yml
.github/workflows/stale.yaml
OWNERS

Fixed https://github.com/serverlessworkflow/sdk-go/issues/115

chore(*): add prow & labeler

---

.github/OWNERS
README.md

Minor patch release to include the CVE fix.

Prepare for release v2.2.1

---

hack/go-lint.sh
model/auth.go
model/function.go
model/object.go
model/states.go
model/workflow.go

Adding missing json tags to Data Model

---

model/event.go

Signed-off-by: Spolti <filippespolti@gmail.com>

json tag missing on Event.Metadata

---

kubernetes/k8s_workflow_integration.go
model/workflow.go

add json tag in the BaseWorkflow

---

model/workflow.go

[States] unknown field defaultCondition

---

model/workflow.go

Accidentally had commented code go through in #192

Remove commented code
