serverlessworkflow/sdk-go

model/function.go, parser/parser_test.go
When parsing the workflow, function.go sets the refname to a hardcoded "refName" string. This skips any refName set in the YAML/JSON.
Instead, we should use the available funcRef map to grab the "refName" value.
Co-PR with @VicNgu
=> Parse funcRef refName correctly

model/function.go
Signed-off-by: mattgarmon <mjg2790@gmail.com>
This PR adds the "graphql" function type to list of function type constants, and adds "selectionSet" to the FunctionRef definition.
GraphQL function type and SelectionSet are defined in the specification here: https://github.com/serverlessworkflow/specification/blob/main/specification.md#using-functions-for-graphql-service-invocations
=> add graphql function type and selectionSet to functionRef

model/event.go, model/states.go, model/workflow.go, parser/parser_test.go, parser/testdata/applicationrequest-issue16.sw.yaml, parser/testdata/applicationrequest.json, parser/testdata/applicationrequest.rp.json, parser/testdata/applicationrequest.url.json, parser/testdata/eventbasedswitch.sw.json, parser/testdata/provisionorders.sw.json
This PR fixes "subflow" states to match what is in the specification: https://github.com/serverlessworkflow/specification/blob/main/specification.md#subflowref-definition
It removes the non-existent "subflow" State type, and adds the "subFlowRef" field to Action.
This also includes removing "workflowId" from other state types, as is is now done via Actions.
By default the "subFlowRef" uses the full object type with "workflowId" and "version" fields, instead of the shorthand notation of just using the workflowId string. This is to be consistent with other fields which can have both string and object values.
=> remove subflow State type, add subFlowRef to Action

model/function.go
Signed-off-by: mattgarmon <mjg2790@gmail.com>
This PR fixes the missing unmarshal for FuntionRef.SelectionSet
The bug was introduced by https://github.com/serverlessworkflow/sdk-go/pull/38
=> fix missing unmarshal for FunctionRef.SelectionSet

go.sum, model/retry.go, parser/parser_test.go, parser/testdata/patientonboarding.sw.yaml, util/floatstr/floatstr.go, util/floatstr/floatstr_test.go
Fixes #36 
@jjrodenburg, can you please take a look? I understand that `float32` can solve this use case. Let me know if not, so we can rethink to `float64`.
=> Fix #36 - Introduce FloatOrString to handle numeric values

model/states.go, parser/parser_test.go, parser/testdata/workflows/eventbasedgreetingexclusive.sw.json, parser/testdata/workflows/eventbasedgreetingnonexclusive.sw.json
Currently, when the exclusive flag is provided, the code will panic due to interface{} unable to be parsed into a (*bool). This change defaults the exclusive flag to true and sets the value if it is provided as a bool.
=> Fix EventState Exclusive parsing interface{} to *bool error

model/auth.go, parser/parser_test.go, parser/testdata/workflows/applicationrequest.json
Signed-off-by: Victor Nguyen <victor.nguyen@acronis.com>
**What this PR does / why we need it**: Auth parsing fails due to Auth.Properties never being set. Properties is already getting unmarshalled, so I just set the Auth.Properties value to the unmarshalled response.
=> Fixed Auth not setting properties field

go.sum, model/auth.go, model/workflow.go, parser/parser_test.go, parser/testdata/workflows/applicationrequest.multiauth.json, parser/testdata/workflows/witherrors/applicationrequest.authdupl.json
Signed-off-by: Davide Salerno <dsalerno@redhat.com>
This change will let you define multiple authentication methods as described in the specifications and highlighted in this [issue](https://github.com/serverlessworkflow/sdk-go/issues/55)
In order to avoid to have different authentication methods with the same name, a new custom validator is added into the auth package
Se the specifications https://github.com/serverlessworkflow/specification/blob/main/specification.md#auth-definition
=> Support multiple Auths

model/retry.go, model/workflow.go
Changed Retry.Multiplier to pointer and changed min=1 (instead of min=0)
in the struct Retry.Multiplier which is a floatstr.Float32OrString, there's no way to distinguish this field as not defined. In the spec, this is supposed to be an optional field. The default struct of Float32OrString will be Type Float and the zero value of FloatVal will be a 0.0 - which will be value if the workflow json/yaml left this out.
Also, minimum of 0 does not make sense
Changed OnError.Transition & OnError.End to pointers for the same reason
=> Changed Retry.Multiplier, OnError.Transition, OnError.End to pointer

parser/parser_test.go
- Fix the error message in unittest
- always check assert.NoError returns, to avoid when error happened, subsequent sentences panic
=> test(*): fix unittest assert.NoError checks and msg

model/auth.go, parser/testdata/workflows/applicationrequest-issue69.json, parser/testdata/workflows/urifiles/auth.json, parser/testdata/workflows/witherrors/applicationrequest.auth.invalid.format.json
- The auth type should be array or string
Fixed https://github.com/serverlessworkflow/sdk-go/issues/69
=> fix(*): update auth type to array or string

go.mod, go.sum, model/delay_state.go, model/delay_state_test.go, model/retry.go, model/retry_test.go, model/states.go, model/util.go, model/util_test.go, model/workflow.go, parser/parser_test.go, parser/testdata/workflows/witherrors/applicationrequest-issue44.json
- Add validation for ISO8601 time duration field
Fixed https://github.com/serverlessworkflow/sdk-go/issues/44
=> fix(44): add validate for ISO8601 time duration field

model/states.go, model/workflow.go, parser/parser_test.go, parser/testdata/workflows/witherrors/applicationrequest-issue74.json
- when transition is missing, validate should failed
- NOTE: we should check the existing validation
Fixed https://github.com/serverlessworkflow/sdk-go/issues/74
=> fix(*): validate failed when transition is missing

go.mod, go.sum, model/auth.go, model/sleep_state.go, model/sleep_state_test.go, model/state_exec_timeout.go, model/state_exec_timeout_test.go, model/states.go, model/workflow.go, parser/testdata/workflows/greetings_sleep.sw.json
- add validator for sleep state field
- refactor StateExecTimeout unmarshal function
=> fix(*): validate stateExecTimeout iso8601

model/event_data_filter.go, model/event_data_filter_test.go, model/workflow.go, parser/testdata/workflows/eventbasedgreeting.sw.json
- add v0.8 eventDataFilter.useData field
Refs: https://github.com/serverlessworkflow/sdk-go/issues/70
=> feat(*): add v0.8 event data filter's useData field

go.mod, go.sum, model/function.go, parser/parser_test.go, parser/testdata/workflows/greetings-custom-function.sw.yaml
=> v08 spec alignment - Support custom function type definition

model/action.go, model/action_data_filter.go, model/action_data_filter_test.go, model/action_test.go, model/function.go, model/workflow.go, parser/testdata/workflows/greetings-constants-file.sw.yaml, parser/testdata/workflows/greetings-secret-file.sw.yaml, parser/testdata/workflows/greetings-secret.sw.yaml, parser/testdata/workflows/greetings.sw.json, parser/testdata/workflows/greetings.sw.yaml, parser/testdata/workflows/greetings_sleep.sw.json
- add v0.8 actionDataFilter.useResults field
Refs: https://github.com/serverlessworkflow/sdk-go/issues/70
=> feat(*): add v0.8 action data filter's useResults field

model/action.go, parser/parser_test.go, parser/testdata/workflows/conditionbasedstate.yaml
add condition statement for action
=> feat(*): add v0.8 action data filter's condition field

model/workflow.go, parser/parser_test.go, parser/testdata/workflows/greetings-v08-spec.sw.yaml
issue: https://github.com/serverlessworkflow/sdk-go/issues/70
=> v08 spec alignment - Workflow name no longer a required property

model/workflow.go, parser/parser_test.go, parser/testdata/workflows/greetings-v08-spec.sw.yaml
Fixes: https://github.com/serverlessworkflow/sdk-go/issues/70
=> v08 spec alignment - Workflow start no longer a required property

README.md, model/event.go, model/event_test.go, parser/testdata/workflows/greetings-v08-spec.sw.yaml
Relates to: https://github.com/serverlessworkflow/sdk-go/issues/70
=> v08 spec aligment - Added resultEventTimeout for action eventref

model/action.go, parser/parser_test.go, parser/testdata/workflows/actiondata-defaultvalue.yaml
Reference to the previous PR, solved the conflicts
https://github.com/serverlessworkflow/sdk-go/pull/88
=> fix useResults no default value bug

parser/parser_test.go
- for %s verbs the value should be string
=> fix(ut): use filename for %s

model/action.go, model/action_test.go, model/auth.go, model/event.go, model/event_test.go, model/state_exec_timeout.go, model/state_exec_timeout_test.go, model/states.go, model/workflow.go, model/workflow_ref.go, model/workflow_test.go, parser/parser_test.go, parser/testdata/workflows/continue-as-example.yaml
=> v08 - fix ContinueAs data field assignment

model/event_state.go, model/event_state_test.go, model/states.go, model/workflow.go
- add OnEvents default ActionMode to `sequential`
=> feat(eventState): add default value `sequential` for OnEvents.ActionMode 

model/action.go, model/action_data_filter.go, model/auth.go, model/delay_state.go, model/event.go, model/event_state.go, model/event_state_test.go, model/retry.go, model/sleep_state.go, model/state_exec_timeout.go, model/states.go, model/util.go, model/workflow.go, parser/parser_test.go, parser/testdata/workflows/eventbaseddataandswitch.sw.json, parser/testdata/workflows/eventbasedswitch.sw.json, parser/testdata/workflows/greetings-v08-spec.sw.yaml
=> fix nill state timeouts and enhance v08 test

model/parallel_state.go, model/parallel_state_test.go, model/states.go, model/workflow.go
- set ParallelState.CompleteType defaults to allOf
- add validate for ParallelState.NumCompleted
Fixed https://github.com/serverlessworkflow/sdk-go/issues/108
=> fix(*): parallelState with completeType defaults to allOf

model/foreach_state.go, model/foreach_state_test.go, model/states.go
Fixed https://github.com/serverlessworkflow/sdk-go/issues/109
=> fix(109): split foreach state to separate file

model/operation_state.go, model/operation_state_test.go, model/states.go
Fixed https://github.com/serverlessworkflow/sdk-go/issues/120
=> fix(121): split operation state to separate file

kubernetes/k8s_workflow_integration.go, model/function.go, model/object.go, model/retry.go, model/switch_state.go, model/workflow.go, parser/parser_test.go, parser/testdata/workflows/greetings-v08-spec.sw.yaml
fixes https://github.com/serverlessworkflow/sdk-go/issues/157
=> Allow the DefaultCondition on events to be string or object

model/function.go
=> Fix small typo on the kubebuilder FunctionType's validation

model/util.go
To build and execute the webassembly in a browser, electron, etc
```bash
GOOS=js GOARCH=wasm $(GO)  build -o out.wasm ./source/
```
In my tests, the only need to change was the file manipulation.
=> Support to WebAssembly build

model/states_validator.go
**What this PR does / why we need it**: This PR fixes issue #181 
I am skipping Transition and End validate tags for states that are used for compensation as "End" should not be defined and Transition is optional for a state that is used for compensation. 
**Additional information (if needed):
If I missed something please let me know I will fix ASAP
=> #181 Skip validTransitionAndEnd for States that are used for compensation

hack/deepcopy-gen.sh, model/foreach_state.go, model/foreach_state_validator_test.go, model/operation_state.go, model/operation_state_validator_test.go
The purpose of this change is to align the workflow validationb between the Java and the GO SDK. Spec allows the action to be a empty list while in the GO SDK, if defined, must have at least one item.
=> relax state action validation

model/workflow.go, model/workflow_validator_test.go
According to the 0.8 spec, we shouldn't be verifying against a list of "accepted" ExpressionLangs, only that `jq` is the default one.
> Serverless Workflow does not mandate the use of jq and it's possible to use an expression language of your choice with the restriction that a single one must be used for all expressions in a workflow definition. If a different expression language needs to be used, make sure to set the workflow expressionLang property to identify it to runtime implementations.
CEL is a commonly used expression language which sees use in implementations of this `sdk-go` library. Support for it as a valid ExpressionLang was removed in or around 4afc5f310fe575b3108e771c8ae11ddde4308e31.
Optimally, …
=> Added CEL to list of valid ExpressionLangs

model/workflow.go, model/workflow_validator_test.go, parser/parser_test.go, parser/testdata/workflows/dataInputSchemaValidation.yaml
Using the "required" tag on the `DataInputSchema.FailOnValidationErrors` field operates counter-intuitively to the go-playground docs. This also causes workflows to fail validation when the value of the field is manually set to `false` because the validator interprets this as the default/unset value.
Not sure where to add a test for this case, need some insight on that front.
Go-playground doc reference: https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Required
> This validates that the value is not the data types default zero value. For numbers ensures value is not zero. For strings ensures value is not "". For slices, maps, pointers, interfaces, channels and …
=> Removed "required" tag from failOnValidationErrors

builder/builder.go, builder/builder_test.go, model/workflow_validator.go, parser/parser.go, parser/parser_test.go
Add support for validating struct built by builder #197
=> Support for validating structs created by builder

hack/deepcopy-gen.sh
chore: Fix go: k8s.io/code-generator/cmd/deepcopy-gen@latest (in k8s.io/code-generator@v0.30.0): go.mod:5: invalid go version '1.22.0': must match format 1.23
=> Pin deepcopy version

go.mod, go.sum, validator/validator.go, validator/validator_test.go
Previously, the library utilized a parsing library for ISO8601 durations that parsed durations into integers only. This caused issues with durations containing fractional values, such as "PT0.5S", which are valid ISO8601 strings but failed to parse due to the limitation of the previous library. 
In this commit, I've replaced the outdated parsing library with a more robust alternative. 
The new library properly handles fractional values, ensuring accurate parsing of ISO8601 duration strings, including cases like "PT0.5S". This update enhances the functionality and reliability of the library by accommodating a broader range of ISO8601 duration formats. Additionally, it ensures compatibility with modern standards and improves the overall usability of the library.
=> fix: ISO8601 duration wouldn't parse for valid fractional values

model/action_validator.go, model/workflow_validator.go, parser/testdata/workflows/compensation.sw.json
=> Fix #195 - Fix 'End' model when `compensate` is defined

config/crd/bases/serverlessworkflow.io_serverlessworkflows.yaml, model/action.go, model/common.go, model/event.go, model/inject_state.go, model/object.go, model/workflow.go, parser/parser_test.go, parser/testdata/workflows/dataInputSchemaNotExists.yaml
Fix #213 
I also added the following annotations:
```
// +kubebuilder:validation:Schemaless
// +kubebuilder:pruning:PreserveUnknownFields
```
To `Metadata` and `Object` attributes since we can't force the type object on Kubernetes context for this type. For example, in the schema use case, the `DataInputSchema` can be a string.
=> Fix #213 - Review DataInputSchema unmarshal function; review k8s annotations for Object type

go.mod
We can't use patch versions in mod files otherwise it may compromise client code.
=> use go 1.22.0 instead of 1.22.8

README.md, impl/ctx/context.go, impl/expr/expr.go, impl/json_pointer.go, impl/json_pointer_test.go, impl/runner.go, impl/runner_test.go, impl/task_runner.go, impl/task_runner_do.go, impl/task_runner_for.go, impl/task_runner_raise.go, impl/task_runner_raise_test.go, impl/task_runner_set.go, impl/testdata/switch_match.yaml, impl/testdata/switch_with_default.yaml, impl/utils.go, model/runtime_expression.go
Fix #233
That was easy and faster than I thought.
=> Fix #233 - Add support to 'switch' task

impl/runner.go, impl/task_runner.go, impl/task_runner_call_http.go, impl/task_runner_do.go, impl/task_runner_for.go, impl/task_runner_raise.go, impl/task_runner_raise_test.go, impl/task_runner_set.go, impl/task_set_test.go
This potentially allows creating TaskRunner object without TaskSupport (so TaskRunners can be reused to execute different workflow instances)
=> Refactoring run method

model/endpoint.go, model/endpoint_test.go
According to the Spec the URI of the Endpoint Configuration can be a template or an expression, when using expressions, the parsing is failing
```json
{
"title": "EndpointConfiguration",
"type": "object",
"unevaluatedProperties": false,
"properties": {
"uri": {
"title": "EndpointUri",
"description": "The endpoint's URI.",
"oneOf": [
{
"title": "LiteralEndpointURI",
"description": "The literal endpoint's URI.",
"$ref": "#/$defs/uriTemplate"
},
{
"title": "ExpressionEndpointURI",
"$ref": "#/$defs/runtimeExpression",
"description": "An expression based endpoint's URI."
}
]
},
"authentication": {
"$ref": "#/$defs/referenceableAuthenticationPolicy",
"title": "EndpointAuthentication", …
```
=> fix: Endpoint configuration should also accept expressions
